baseURL = 'https://elecbrandy.github.io/freshpink/'
languageCode = 'en-us'
title = 'FreshPink'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'tags'
pageRef = '/tags'
weight = 20

[[menus.main]]
name = 'about'
pageRef = '/about'
weight = 30

[module]
  [module.hugoVersion]
    extended = true
    min = "0.116.0"

[params]
  githubUsername = "elecbrandy"
  copyright = "Copyright Â© 2023 elecbrandy"

[taxonomies]
  tag = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
